version: '3'

volumes:
  supervisor_odoo_data: {}
  supervisor_odoo_db: {}

services:
    broker:
      build:
        context: mosquitto
        dockerfile: Dockerfile 
      ports:
        - "1883:1883"
        - "8883:8883"
      volumes:
        - ./mosquitto/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      environment:
        - DB=test
        - DB_USER=odoo
        - DB_PASSWORD=odoo
        - DB_HOST=db

    odoo:
      build:
        context: .
        dockerfile: odoo/Dockerfile
      depends_on:
        - db
      ports:
        - "8069:8069"
      volumes:
        - "supervisor_odoo_data:/var/lib/odoo"
        - "./addons/device_manager/:/mnt/extra-addons/device_manager/"
        - "./mosquitto/addons/mosquitto/:/mnt/extra-addons/mosquitto/"
      command: ["odoo", "--workers=0", "--db-filter=test", "--database=test", "--log-level=debug"]

    db:
      image: postgres:9-alpine
      environment:
        - POSTGRES_PASSWORD=odoo
        - POSTGRES_USER=odoo
      volumes:
        - supervisor_odoo_db:/var/lib/db

    http_bridge:
      image: litnimax/mqttrpc_http_bridge
      environment:
        - HTTP_URL=http://odoo:8069/jsonrpc
        - HTTP_LISTEN_ADDRESS=0.0.0.0
        - HTTP_LISTEN_PORT=8888
        - MQTT_URL=mqtt://http_bridge:jdhm923KsNTS73HsnJ@broker
        - CLIENT_UID=odoo
        - DEBUG=1
        - MQTT_REPLY_TIMEOUT=60

    manager:
      build:
        context: .
        dockerfile: manager/Dockerfile
      environment:
        - ODOO_DB=test
        - ODOO_USER=admin
        - ODOO_PASSWORD=admin
        - CLIENT_UID=manager
        - MQTT_URL=mqtt://manager:djh37Ha0hs3jiwHJ73@broker
      volumes:
        - ./manager.py:/app/manager.py
  
